
INSERT INTO public.portfolio_projects (slug, title, category, client, summary, cover_url, tags, published, featured, sort_order, completed_at) VALUES
('lekki-residence-cctv','16-Camera CCTV & Smart Access at Lekki Residence','Home Security','Private Residence, Lekki','Full-perimeter 4K CCTV, NVR with 30-day cloud backup, and app-controlled smart locks across a 5-bedroom duplex.', null, ARRAY['CCTV','Smart Locks','Cloud Monitoring'], true, true, 1, '2026-05-10'),
('abuja-fintech-marketing','Fintech Growth: 4x Organic Traffic in 90 Days','Digital Marketing','Abuja Fintech Startup','Technical SEO overhaul, content programme and paid-search retargeting that grew qualified sign-ups by 220%.', null, ARRAY['SEO','Google Ads','Content'], true, true, 2, '2026-04-01'),
('naija-fashion-ecom','E-commerce Rebuild for a Nigerian Fashion Brand','Web Design','Fashion DTC Brand','Rebuilt Shopify-style storefront on a fast React stack with WhatsApp checkout and Paystack — 38% faster LCP.', null, ARRAY['E-commerce','React','Paystack'], true, false, 3, '2026-03-18'),
('estate-access-control','Estate-wide Access Control, Ikoyi','Home Security','Ikoyi Estate','Boom barriers, RFID cards and license-plate cameras across 4 gates, unified in a single guardhouse dashboard.', null, ARRAY['Access Control','LPR','Estate'], true, false, 4, '2026-02-02');

INSERT INTO public.blog_posts (slug, title, excerpt, content, tags, author_name, published, published_at, reading_minutes) VALUES
('choosing-cctv-nigerian-home','How to Choose CCTV for a Nigerian Home in 2026','2K vs 4K, PoE vs Wi-Fi, and why cloud backup matters when NEPA takes the light.','## The short version\n\nFor most Nigerian homes, a 4-camera PoE NVR system with 2K cameras and a UPS-backed NVR is the sweet spot.\n\n## What to look for\n\n- **Resolution**: 2K (4MP) is the new baseline. 4K only where you need to read license plates.\n- **Power over Ethernet**: fewer cables, no Wi-Fi drops.\n- **Local + cloud recording**: on-site NVR for speed, cloud for burglary/fire.\n- **UPS**: 30–60 minutes of runtime keeps you covered through short outages.\n\n## Common mistakes\n\n1. Buying the cheapest cameras and skipping the NVR quality.\n2. No UPS on the recorder — losing footage during outages.\n3. Weak passwords on the mobile app.', ARRAY['CCTV','Buyer Guide'], 'Nexashield Team', true, now() - interval '7 days', 6),
('seo-for-lagos-businesses','SEO That Actually Works for Lagos Businesses','Local packs, GMB, and the three on-page fixes that matter most for Nigerian SMBs.','## Start with Google Business Profile\n\nClaim, verify, add photos weekly, and reply to every review — including one-star ones.\n\n## On-page basics\n\n- Unique title & meta per page\n- One H1 per page, keyword in first paragraph\n- Fast mobile pages — LCP under 2.5s on 4G\n\n## Content cadence\n\nOne useful post per week beats ten thin posts per month. Answer real questions from your customers.', ARRAY['SEO','Local'], 'Nexashield Team', true, now() - interval '3 days', 5);
